# Generated by Django 3.2 on 2021-04-22 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.IntegerField(default=None)),
                ('icon', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=35)),
                ('amount', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=25)),
                ('adres', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('sity', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Registr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('passvord', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField(max_length=700)),
                ('photo', models.ImageField(upload_to='images')),
                ('price', models.IntegerField()),
                ('create_at', models.DateTimeField()),
                ('views', models.IntegerField(default=None)),
                ('sale', models.IntegerField()),
                ('status', models.CharField(choices=[(1, 'ACTIVE'), (2, 'INACTIVE'), (3, 'SOLD'), (3, 'EXPIRED')], max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.category')),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.poster')),
            ],
        ),
        migrations.AddField(
            model_name='poster',
            name='registr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.registr'),
        ),
    ]
